name: Aqua
on: 
  pull_request:
  push:
jobs:
  aqua:
    name: Aqua scanner
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: read
      security-events: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Decode Sysdig Token from Secrets
        id: decode_token
        run: |
          echo "SYSDIG_SECURE_TOKEN=$(echo '${{ secrets.SYSDIG_SECURE_TOKEN_B64 }}' | base64 -d)" >> $GITHUB_ENV

      - name: Sysdig Image Scan
        id: sysdig-scan
        uses: sysdiglabs/scan-action@v5
        with:
          sysdig-secure-token: ${{ env.SYSDIG_SECURE_TOKEN }}
          mode: iac
          iac-scan-path: . 
          
      - name: Upload SARIF Report to GitHub Security Tab
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ github.workspace }}/sarif.json
